object Versions {

    const  val coil="1.4.0"
    const val crashlytics = "2.7.1"
    const val gradle = "7.0.2"
    const val google_service = "4.3.10"
    const val http_logger = "4.9.1"
    const val webkit = "1.4.0"
    const val browser = "1.3.0"
    const val glide = "4.12.0"
    const val hilt_nav = "1.0.0"
    const val lottie = "3.4.1"
    const val paging = "3.0.0"
    const val kotlin = "1.5.0"
    const val kotlin_version = "1.5.30"
    const val room_version = "2.3.0"
    const val lifecycle_version = "2.3.1"
    const val lifecycle_extensions = "2.2.0"
    const val hilt_view_models = "1.0.0-alpha03"
    const val hilt_version = "2.38.1"
    const val billing_version = "4.0.0"
    const val junit = "4.13.2"
    const val junit_ext = "1.1.2"
    const val espresso = "3.3.0"
    const val material = "1.2.0-alpha06"
    const val swiperefreshlayout = "1.1.0"
    const val appcompat = "1.3.0"
    const val core_ktx = "1.5.0"
    const val constraintlayout = "2.1.0"
    const val recyclerview = "1.2.1"
    const val retrofit = "2.9.0"
    const val data_binding = "3.6.1"
    const val play_core_ktx = "1.8.1"
    const val preference = "1.1.1"

    const val firebase_analytics="19.0.0"
    const val firebase_config="21.0.0"
    const val firebase_messaging="22.0.0"
    const val firebase_crashlytics = "18.2.1"

    const val nav_version="2.3.5"
    const val shimmer="0.5.0"
    const val palette="1.0.0"


}